#!/bin/bash
set -eu
shopt -s extglob
shopt -s globstar


COVERAGE=coverage

.bin/deno cache **/*.js
.bin/deno coverage $COVERAGE --exclude=.test --lcov --output=cov_profile.lcov
.bin/deno coverage $COVERAGE --exclude=.test