#!/bin/bash
set -eu
shopt -s extglob
shopt -s globstar

SRC_DIR=src
TEST_DIR=tests

echo
echo "Downloading local copies of the imports in $SRC_DIR and $TEST_DIR"
./.bin/deno vendor $SRC_DIR/**/*.js $TEST_DIR/**/*.js --force --import-map=import_map.json &> /dev/null
echo "Combined import map created at vendor/import_map.json."
echo "To change the import map, edit your original import map in project root and re-run tasks/vendor"
echo